defaults: &defaults
  app_name: "Wuxian Beta"
  facebook_app_id: "329818377221449"
  facebook_secret: "1853e405f2928fcd1c1de9ebce4b7e39"

  disqus:
    short_name: "test4wuxian"
    secret_key: "u7Zwyg9KF8wC7dZzAgQ6VCOzs7y69BtQA6I6j4lI01mKYyZFI84tJH6P5F3jjWld"
    public_key: "6jvmPJvtNXmxkRMDs72gTqu3EWy2Tbu4WH8jbyCPnc5sg2lmNhOcddRsizOrSxSE"
    access_token: "4f3d7c287836445089265de2e939d700"

development:
  <<: *defaults
  domain: "http://wuxian-rails.dev"

test:
  <<: *defaults

production:
  <<: *defaults
